type PostType = {
  title: string;
  slug: string;
  author: string;
  date: string;
  category: string;
  thumbnail: string;
  description: string;
  tags: string[];
};

export const posts: PostType[] = [
  {
    title: "Votre site web est-il prêt pour 2026 ?",
    slug: "site-web-optimise-2026",
    author: "Webcreatis",
    date: "13-01-2026",
    category: "Développement web",
    thumbnail: "/images/thumbnails/site-web-optimise-2026.webp",
    tags: [
      "site web 2026",
      "optimisation site web",
      "performance web",
      "SEO 2026",
      "référencement web",
      "accessibilité web",
      "responsive design",
      "WebCreatis",
      "freelance web",
      "refonte site internet",
    ],
    description:
      "Découvrez comment préparer votre site web pour 2026 : performance, sécurité, référencement et expérience utilisateur. Un site optimisé n’est plus une option, c’est une nécessité.",
  },
  {
    title: "Qu’est-ce que le Generative Engine Optimization (GEO) ?",
    slug: "qu-est-ce-que-le-generative-engine-optimization-geo",
    author: "Webcreatris",
    date: "08-07-2025",
    category: "SEO",
    thumbnail: "/images/thumbnails/geo-webcreatis.webp",
    tags: [
      "Generative Engine Optimization",
      "GEO SEO IA",
      "référencement IA générative",
      "optimisation contenu pour IA",
      "SEO pour ChatGPT",
      "SEO pour Google SGE",
      "référencement futuriste",
      "SEO vs GEO",
      "SEO IA 2025",
      "référencement local IA",
      "contenu structuré pour IA",
      "optimisation pour moteur d’IA",
      "visibilité dans l’IA générative",
      "ChatGPT et SEO",
      "Google Search Generative Experience",
      "balisage sémantique IA",
      "WebCreatris SEO La Réunion",
      "agence SEO IA Réunion",
      "nouvelle stratégie de contenu 2025",
      "IA générative et marketing digital",
    ],
    description:
      "Le Generative Engine Optimization (GEO) est la nouvelle stratégie SEO pour rendre votre contenu visible dans les moteurs de réponse IA comme ChatGPT ou Google SGE. Découvrez comment adapter votre contenu à l’ère de l’intelligence artificielle.",
  },
  {
    title:
      "Pourquoi utiliser Next.js pour n’importe quel projet informatique ?",
    slug: "pourquoi-utiliser-nextjs-pour-votre-projet",
    author: "Webcreatis",
    date: "01-06-2025",
    category: "Framework",
    thumbnail: "/images/thumbnails/pourquoi-nextjs.webp",
    tags: [
      "Next.js framework React",
      "framework JavaScript fullstack",
      "choisir Next.js pour un projet web",
      "Next.js ou React pur",
      "Next.js 15 nouvelles fonctionnalités",
      "optimisation performance Next.js",
      "rendu serveur SSR avec Next.js",
      "génération statique SSG Next.js",
      "ISR Next.js incremental static regeneration",
      "hydration React Next.js",
      "optimisation images WebP Next.js",
      "lazy loading automatique Next.js",
      "code splitting Next.js",
      "SEO optimisé avec Next.js",
      "Next.js et référencement naturel",
      "balises meta dynamiques Next.js",
      "création sitemap avec Next.js",
      "hot reload Next.js",
      "support TypeScript dans Next.js",
      "création API REST avec Next.js",
      "utilisation middleware Edge Next.js",
      "routage dynamique Next.js",
    ],
    description:
      "Next.js est devenu l’un des frameworks les plus populaires pour construire des applications full stack modernes",
  },
  {
    title: "Comment activer Fluid Compute sur vercel",
    slug: "activer-fluid-compute-cloud-scalabilite-performance",
    author: "Webcreatis",
    date: "20-05-2025",
    category: "devops",
    thumbnail: "/images/thumbnails/vercel-fluid-compute.webp",
    tags: [
      "activer Fluid Compute sur Vercel",
      "utiliser Fluid Compute avec Next.js",
      "Fluid Compute configuration",
      "optimiser déploiement Vercel Fluid Compute",
      "différence entre Edge Functions et Fluid Compute",
      "hébergement serverless Vercel",
      "hébergement web vercel",
      "avantages Fluid Compute Vercel pour performance web",
      "meilleure méthode pour activer Fluid Compute",
      "performances dynamiques cloud Vercel",
      "serverless computing moderne",
      "enable Fluid Compute Vercel",
      "Vercel Fluid Compute tutorial",
      "dynamic serverless scaling Vercel",
      "Fluid Compute performance boost",
    ],
    description:
      "Fluid Compute par Vercel optimise vos applications avec une allocation dynamique des ressources pour performance, scalabilité et réduction des coûts.",
  },
  {
    title: "7 erreurs à éviter quand on crée son site web",
    slug: "7-erreurs-a-eviter-creation-site-web",
    author: "Webcreatis",
    date: "24-09-2025",
    category: "Création de site web",
    thumbnail: "/images/thumbnails/erreurs-creation-site-internet.webp",
    tags: [
      "erreurs site web",
      "création site internet",
      "refonte site web",
      "optimisation UX",
      "SEO site web",
      "design web 2025",
      "site web performant",
      "checklist site web",
      "site responsive",
      "agence web",
      "call-to-action",
      "temps de chargement",
      "design moderne",
      "webcreatis",
      "bonnes pratiques site web",
      "site vitrine",
      "expérience utilisateur",
      "ergonomie site web",
      "création site web professionnel",
      "conversion clients site web",
    ],
    description:
      "Découvrez les 7 erreurs les plus fréquentes lors de la création d’un site internet et comment les éviter pour transformer votre site en véritable générateur de clients.",
  },
  {
    title: "Accessibilité Web : les nouvelles règles 2025",
    slug: "accessibilite-web-RGAA-2025",
    author: "Webcreatis",
    date: "13-10-2025",
    category: "Accessibilité web",
    thumbnail: "/images/thumbnails/accessibilite-web-rgaa-2025.webp",
    tags: [
      "accessibilité web",
      "wcag 3.2",
      "loi numérique",
      "inclusion digitale",
      "site web accessible",
      "conformité 2025",
      "ux accessible",
      "design inclusif",
      "audit accessibilité",
      "accessibilité mobile",
      "normes web",
      "ergonomie web",
      "technologies assistives",
      "alt texte",
      "contraste couleur",
      "navigation clavier",
      "webcreatis",
      "audit site",
      "accessibilité numérique",
      "site inclusif",
    ],
    description:
      "Découvrez les nouvelles règles d’accessibilité web 2025 pour rendre votre site conforme, inclusif et utilisable par tous. Apprenez les bonnes pratiques pour garantir l’accessibilité et l’expérience utilisateur optimale.",
  },
  {
    title: "Generative SEO : prépare ton site pour l’IA",
    slug: "generative-seo-prepare-ton-site-pour-ia",
    author: "Webcreatis",
    date: "09-10-2025",
    category: "SEO",
    thumbnail: "/images/thumbnails/generative-seo.webp",
    tags: [
      "generative seo",
      "geo",
      "intelligence artificielle",
      "référencement",
      "seo 2025",
      "search generative experience",
      "optimisation contenu ia",
      "perplexity",
      "chatgpt seo",
      "future du seo",
      "ai search",
      "agence seo",
      "strategie contenu",
      "optimisation site web",
      "webcreatis",
      "autorité de site",
      "donnees structurees",
      "seo technique",
      "visibilité ia",
      "referencement naturel",
    ],
    description:
      "Apprenez comment préparer votre site web à l’ère de l’intelligence artificielle grâce au Generative Engine Optimization (GEO). Découvrez les clés pour que votre contenu soit compris et cité par les moteurs d’IA.",
  },
];
